name: Main CI CD Pipeline

permissions:
  contents: read
  packages: write

# checkov:skip=CKV_GHA_7: Manual deployment input is required by design

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Choose Deployment Environment"
        required: true
        type: choice
        options:
          - local
          - ec2

jobs:

  # ======================
  # JOB 1 - BUILD IMAGE
  # ======================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t solar-system-app:${{ github.sha }} .

      - name: Save Docker Image
        run: |
          docker save solar-system-app:${{ github.sha }} > image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


  # ======================
  # JOB 2 - TRIVY SCAN
  # ======================
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: |
          docker load < image.tar

      - name: Trivy Scan Image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: solar-system-app:${{ github.sha }}
          format: html
          output: trivy-report.html
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.html


  # ======================
  # JOB 3 - PUSH IMAGE
  # ======================
  push-image:
    runs-on: ubuntu-latest
    needs: trivy-scan

    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: |
          docker load < image.tar

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker tag solar-system-app:${{ github.sha }} \
          ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest


  # ======================
  # CD JOB
  # ======================
  cd:
    runs-on: ubuntu-latest
    needs: push-image

    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy Local
        if: github.event.inputs.deploy_target == 'local'
        run: |
          docker run -d -p 3000:3000 \
          ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest

      - name: Deploy EC2
        if: github.event.inputs.deploy_target == 'ec2'
        run: |
          echo "Deploying to EC2..."
