name: Main CI CD Pipeline

permissions:
  contents: read
  packages: write
  security-events: write

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

# =========================
# BUILD IMAGE
# =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t solar-system-app:latest .

      - name: Save Image
        run: |
          docker save solar-system-app:latest > image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


# =========================
# TRIVY SECURITY SCAN
# =========================
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Image
        run: docker load < image.tar

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: solar-system-app:latest
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Save Trivy Report
        run: |
          trivy image solar-system-app:latest --format table > trivy-report.txt

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt


# =========================
# PUSH IMAGE TO DOCKERHUB
# =========================
  push-image:
    runs-on: ubuntu-latest
    needs: trivy-scan

    steps:
      - name: Download Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Image
        run: docker load < image.tar

      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag & Push Image
        run: |
          docker tag solar-system-app:latest ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest


# =========================
# DEPLOY TO EC2
# =========================
  deploy:
    runs-on: ubuntu-latest
    needs: push-image

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy On EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            docker pull ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest

            docker stop solar-system || true
            doc
