name: Main CI CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

# =========================
# JOB 1 â€” BUILD IMAGE
# =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t solar-system-app:latest .

      - name: Save Docker Image
        run: |
          docker save solar-system-app:latest > image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


# =========================
# JOB 2 â€” TRIVY SCAN
# =========================
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: |
          docker load < image.tar

      - name: Install Trivy
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Run Trivy Scan (Generate Report)
        run: |
          trivy image solar-system-app:latest \
          --format table \
          --output trivy-report.txt

      - name: Upload Trivy Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.txt


# =========================
# JOB 3 â€” PUSH IMAGE
# =========================
  push-image:
    runs-on: ubuntu-latest
    needs: trivy-scan

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: |
          docker load < image.tar

      - name: Login To DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag & Push Image
        run: |
          docker tag solar-system-app:latest ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest


# =========================
# JOB 4 â€” DEPLOY (MANUAL)
# =========================
  deploy:
    runs-on: ubuntu-latest
    needs: push-image
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy Message
        run: |
          echo "Deploy Started Successfully ðŸš€"
