name: Main CI CD Pipeline

permissions:
  contents: read
  packages: write
  security-events: write

on:
  push:
    branches:
      - main
      - hager/task1

  workflow_dispatch:

jobs:

# =========================
# BUILD
# =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t solar-system-app:${{ github.sha }} .

      - name: Save Image
        run: docker save solar-system-app:${{ github.sha }} > image.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


# =========================
# TRIVY SCAN
# =========================
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - run: docker load < image.tar

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: solar-system-app:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 0


# =========================
# PUSH IMAGE
# =========================
  push-image:
    runs-on: ubuntu-latest
    needs: trivy-scan

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - run: docker load < image.tar

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag & Push
        run: |
          docker tag solar-system-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest


# =========================
# MANUAL DEPLOY
# =========================
  deploy:
    runs-on: ubuntu-latest
    needs: push-image
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy
        run: echo "Manual Deployment Triggered"
