name: Main CI CD Pipeline

permissions:
  contents: read
  packages: write
  security-events: write

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

# =========================
# BUILD IMAGE
# =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t solar-system-app:latest .

      - name: Save Image
        run: |
          docker save solar-system-app:latest > image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


# =========================
# TRIVY SCAN
# =========================
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Image
        run: docker load < image.tar

      - name: Install Trivy
        run: |
          sudo apt install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Run Trivy Scan
        run: |
          trivy image solar-system-app:latest \
          --format table \
          --output trivy-report.txt

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt


# =========================
# PUSH IMAGE
# =========================
  push-image:
    runs-on: ubuntu-latest
    needs: trivy-scan

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Image
        run: docker load < image.tar

      - name: DockerHub Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Image
        run: |
          docker tag solar-system-app:latest ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest


# =========================
# DEPLOY TO EC2
# =========================
