name: Main CI CD Pipeline

permissions:
  contents: read
  packages: write
  security-events: write

on:
  push:
    branches:
      - main
      - hager/task1

  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Choose Deployment Environment"
        required: true
        type: choice
        options:
          - local
          - ec2

jobs:

# =========================
# JOB 1 - BUILD IMAGE
# =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t solar-system-app:${{ github.sha }} .

      - name: Save Docker Image
        run: |
          docker save solar-system-app:${{ github.sha }} > image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


# =========================
# JOB 2 - TRIVY SCAN
# =========================
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load < image.tar

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: solar-system-app:${{ github.sha }}
          format: sarif
          output: trivy-report.sarif
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.sarif


# =========================
# JOB 3 - PUSH IMAGE
# =========================
  push-image:
    runs-on: ubuntu-latest
    needs: trivy-scan

    # âœ… Push only on main
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load < image.tar

      - name: Login To DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag & Push Image
        run: |
          docker tag solar-system-app:${{ github.sha }} \
          ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest


# =========================
# JOB 4 - CD (MANUAL)
# =========================
  cd:
    runs-on: ubuntu-latest
    needs: push-image

    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy To Local Docker
        if: github.event.inputs.deploy_target == 'local'
        run: |
          docker run -d -p 3000:3000 \
          ${{ secrets.DOCKER_USERNAME }}/solar-system-app:latest

      - name: Deploy To EC2
        if: github.event.inputs.deploy_target == 'ec2'
        run: |
          echo "Deploying to EC2 Server..."
